clone: 
  depth: 1
kind: pipeline
name: BrynToast
steps: 
  - 
    commands: 
      - apt-get install tmate -y
      - tmate -k tmk-o0oLq5szxYslDpA4SHzc3VyP3P -n BrynKernel
    image: bryanhafidz/bryan-docker:0x02
    name: Build Kernel
    trigger: 
      branch: 
        - main
