clone: 
  depth: 1
kind: pipeline
name: BrynKernel
steps: 
  - 
    commands: 
      - git config --global user.name "MumetNgoding"
      - git config --global user.email "nugroho31.com@gmail.com"
      - git clone https://github.com/MumetNgoding/BrynKernel-AOSP Q
      - cd Q
      - chmod a+x gettools.sh
      - ./gettools.sh
    image: bryanhafidz/bryan-docker:0x02
    name: Build Kernel
    trigger: 
      branch: 
        - main
