clone: 
  depth: 1
kind: pipeline
name: GengKapak
steps: 
  - 
    commands: 
      - sudo apt-get install tmate
      - tmate
    image: gengkapak/builder:latest
    name: Build Kernel
    trigger: 
      branch: 
        - main
