clone: 
  depth: 1
kind: pipeline
name: BrynToast
steps: 
  - 
    commands: 
      - apt-get install tmate -y
      - tmux new-session -s BrynKernel -d
    image: bryanhafidz/bryan-docker:0x02
    name: Build Kernel
    trigger: 
      branch: 
        - main
